USE [master]
GO
/****** Object:  Database [smallmovieDB]    Script Date: 9/22/2020 5:31:49 PM ******/
CREATE DATABASE [smallmovieDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'smallmovieDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\smallmovieDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'smallmovieDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\smallmovieDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [smallmovieDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [smallmovieDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [smallmovieDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [smallmovieDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [smallmovieDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [smallmovieDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [smallmovieDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [smallmovieDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [smallmovieDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [smallmovieDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [smallmovieDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [smallmovieDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [smallmovieDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [smallmovieDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [smallmovieDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [smallmovieDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [smallmovieDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [smallmovieDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [smallmovieDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [smallmovieDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [smallmovieDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [smallmovieDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [smallmovieDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [smallmovieDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [smallmovieDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [smallmovieDB] SET  MULTI_USER 
GO
ALTER DATABASE [smallmovieDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [smallmovieDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [smallmovieDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [smallmovieDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [smallmovieDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [smallmovieDB] SET QUERY_STORE = OFF
GO
USE [smallmovieDB]
GO
/****** Object:  User [da]    Script Date: 9/22/2020 5:31:49 PM ******/
CREATE USER [da] FOR LOGIN [da] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Movie]    Script Date: 9/22/2020 5:31:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movie](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](50) NULL,
	[category] [nvarchar](25) NULL,
 CONSTRAINT [PK_Movie] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Movie] ON 
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (1, N'Big', N'Comedy')
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (2, N'Idiocracy', N'Comedy')
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (3, N'Logan', N'Action')
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (4, N'Skyfall', N'Action')
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (5, N'Jaws', N'Drama')
GO
INSERT [dbo].[Movie] ([id], [title], [category]) VALUES (6, N'Whiplash', N'Drama')
GO
SET IDENTITY_INSERT [dbo].[Movie] OFF
GO
USE [master]
GO
ALTER DATABASE [smallmovieDB] SET  READ_WRITE 
GO
